# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app
COPY . .

# Install dependencies
# COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# # Set environment variables for Flask
ENV FLASK_APP=run.py:create_app
ENV FLASK_ENV='production'
ENV FLASK_DEBUG=1
# ENV DATABASE_URL=postgresql://postgres:pass@123@moviereservationpostgresdb:5432/ticketing_service 

# Command to run the Flask app

# CMD ["flask", "run", "--host=0.0.0.0:8083"]
CMD ["sh", "entrypoint.sh"]

