# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the application JAR file to the container
COPY target/theaterservice-0.0.1-SNAPSHOT.jar theater-service.jar

# Define the command to run the application
ENTRYPOINT ["java", "-jar", "theater-service.jar"]
